/*AmpShell : .NET front-end for DOSBox
 * Copyright (C) 2009, 2019 Maximilien Noal
 *This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program.
 * If not, see <http://www.gnu.org/licenses/>.*/

using System;
using System.IO;

namespace AmpShell.AutoConfig
{
    public static class FileFinder
    {
        public static bool HasWriteAccessToAssemblyLocationFolder()
        {
            try
            {
                if( Directory.GetDirectoryRoot(PathFinder.GetStartupPath()) == Environment.GetFolderPath(System.Environment.SpecialFolder.ProgramFiles) ||
                    Directory.GetDirectoryRoot(PathFinder.GetStartupPath()) == Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86))
                {
                    return false;
                }
                string tmpFilePath = Path.Combine(PathFinder.GetStartupPath(), Path.GetRandomFileName());
                while (File.Exists(tmpFilePath) == true)
                {
                    tmpFilePath = Path.Combine(PathFinder.GetStartupPath(), Path.GetRandomFileName());
                }
                File.Create(tmpFilePath, 1, FileOptions.DeleteOnClose).Close();
                return true;
            }
            catch (UnauthorizedAccessException)
            {
                return false;
            }
        }

        public static string SearchCommonTextEditor()
        {
            string confEditorPath = string.Empty;
            if (string.IsNullOrWhiteSpace(confEditorPath))
            {
                string notepadPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Windows), "notepad.exe");
                if (File.Exists(notepadPath))
                {
                    confEditorPath = notepadPath;
                }
            }
            return confEditorPath;
        }

        public static string SearchDOSBoxConf(string userConfigDataPath, string DOSBoxExecutablePath)
        {
            string confPath = string.Empty;
            if (userConfigDataPath == PathFinder.GetStartupPath() + "\\AmpShell.xml")
            {
                if (Directory.GetFiles((PathFinder.GetStartupPath()), "*.conf").Length > 0)
                {
                    confPath = Directory.GetFiles((PathFinder.GetStartupPath()), "*.conf")[0];
                }
            }
            if (string.IsNullOrWhiteSpace(confPath))
            {
                //if Local Settings/Application Data/DOSBox exists
                if (Directory.Exists(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData) + "\\DOSBox"))
                {
                    //then, the DOSBox.conf file inside it becomes the default one.
                    if (Directory.GetFiles(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData) + "\\DOSBox", "*dosbox*.conf").Length > 0)
                    {
                        confPath = Directory.GetFiles(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData) + "\\DOSBox", "*dosbox*.conf")[0];
                    }
                }
                else
                {
                    //if dosbox.conf has been generated by DOSBox in the same directory as dosbox.exe
                    //(behavior of DOSBox versions prior to DOSBox version 0.73)
                    if (string.IsNullOrWhiteSpace(DOSBoxExecutablePath) == false)
                    {
                        if (File.Exists(Path.GetDirectoryName(DOSBoxExecutablePath) + "\\dosbox.conf"))
                        {
                            confPath = DOSBoxExecutablePath + "\\dosbox.conf";
                        }
                    }
                }
            }
            return confPath;
        }

        public static string SearchDOSBoxLanguageFile(string dosboxExecutablePath)
        {
            //returned string
            string langPath = string.Empty;
            //if LangPath is _still_ empty, Windows test cases take place.
            if (string.IsNullOrWhiteSpace(langPath))
            {
                //if Local Settings/Application Data/DOSBox exists
                if (Directory.Exists(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData) + "\\DOSBox"))
                {
                    //then, the DOSBox.conf file inside it becomes the default one.
                    if (Directory.GetFiles(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData) + "\\DOSBox", "*.lng").Length > 0)
                    {
                        langPath = Directory.GetFiles(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData) + "\\DOSBox", "*.lng")[0];
                    }
                }
                else
                {
                    //if dosbox.conf has been generated by DOSBox in the same directory as dosbox.exe
                    //(behavior of DOSBox versions prior to DOSBox version 0.73)
                    if (string.IsNullOrWhiteSpace(dosboxExecutablePath) == false)
                    {
                        if (Directory.GetFiles(Path.GetDirectoryName(dosboxExecutablePath), "*.lng").Length > 0)
                        {
                            langPath = Directory.GetFiles(Path.GetDirectoryName(dosboxExecutablePath), "*.lng")[0];
                        }
                    }
                }
            }
            return langPath;
        }

        public static string SearchDOSBox(string userConfigDataPath, bool portableMode)
        {
            string dosboxPath = string.Empty;
            if (userConfigDataPath == PathFinder.GetStartupPath() + "\\AmpShell.xml" && portableMode)
            {
                if (File.Exists(PathFinder.GetStartupPath() + "\\dosbox.exe"))
                {
                    dosboxPath = PathFinder.GetStartupPath() + "\\dosbox.exe";
                }
            }
            else
            {
                //test if DOSBox is in Program Files/DOSBox-?.?? (Windows x86)
                if (Directory.GetDirectories(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles), "DOSBox*", SearchOption.TopDirectoryOnly).GetLength(0) != 0)
                {
                    dosboxPath = Directory.GetDirectories(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles), "DOSBox*", SearchOption.TopDirectoryOnly)[0];
                    if (File.Exists(dosboxPath + "\\dosbox.exe"))
                    {
                        dosboxPath += "\\dosbox.exe";
                    }
                }
                else
                {
                    //test if the user is using Windows x64
                    //in this case, DOSBox's installation directory is most likely in "Program Files (x86)"
                    if (Directory.Exists(Environment.SystemDirectory.Substring(0, 3) + "Program Files (x86)"))
                    {
                        if (Directory.GetDirectories(Environment.SystemDirectory.Substring(0, 3) + "Program Files (x86)", "DOSBox*", SearchOption.TopDirectoryOnly).GetLength(0) != 0)
                        {
                            dosboxPath = Directory.GetDirectories(Environment.SystemDirectory.Substring(0, 3) + "Program Files (x86)", "DOSBox*", SearchOption.TopDirectoryOnly)[0];
                            if (File.Exists(dosboxPath + "\\dosbox.exe"))
                            {
                                dosboxPath += "\\dosbox.exe";
                            }
                        }
                    }
                }
            }
            return dosboxPath;
        }
    }
}